### ISSUE TITLE
[FEATURE] 앱 내에서 동영상만 볼 수 있도록 변경

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#103]
## Description

- 운동 화면의 상단에 동영상만 재생되도록 변경

## Tasks

- [x] 라이브러리 추가해서 동영상만 재생되도록 함
- [x] 하단의 동영상 목록을 탭했을 때 해당 동영상이 재생되도록 함
- [x] 검색 화면에서 동영상 플레이어 화면으로 이동하도록 변경
