### ISSUE TITLE
[DESIGN] Search View 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#23]
## Description

- Search View 구성

## Tasks

- [x] SearchBar 추가
- [x] 최근 검색어 CollectionView 추가
- [x] 최근 검색어 전체 삭제 추가
- [x] 메모, 동영상 SegmentedControler 추가 
- [x] 검색 결과 TableView 추가
