### ISSUE TITLE
[DESIGN] 1차 UI 피드백

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#28]
## Description

- 1차 UI 피드백하고 부족한 부분 수정

## Tasks

- [x] 내 정보: 안녕하세요 label 올리기
- [x] 내 정보: 저장 버튼과 겹치는 부분 수정
- [x] 식단: 기본 이미지 지정
- [x] 식단: Meal view와 Meal edit view 연결
- [x] 식단: Meal edit view title 설정
- [x] 식단: Meal edit view 배경색 맞추기
- [x] 운동: 옵션 이미지 지정
- [x] 운동: Category view와 Exercise edit view, Category edit view 연결
- [x] 운동: Exercise view title label 줄 수 무한하게 변경
- [x] 운동: gray view 탭했을 때 toggle 하도록 함
- [x] 운동: Category Option button 위치 변경
- [x] TabBar: select 색깔 변경
- [x] 운동: Category selecte edit View 색깔 통일하기
- [x] 운동: Category selecte edit View의 back 삭제
