### ISSUE TITLE
[DESIGN] MyInfo View 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#3]
## Description

- MyInfo View 구성

## Tasks

- [x] BaseViewController에 TopView 추가
- [x] 인사 및 닉네임 label 추가
- [x] 캘린더 추가
- [x] 내 정보 label 추가
- [x] 체중, 골격글냘, 체지방률 view 각각 추가
- [x] 플로팅 버튼 추가
