### ISSUE TITLE
[FEATURE] MyInfo View 기능 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#36]
## Description

- MyInfo View 기능 추가

## Tasks

- [x] 닉네임 화면에 표시
- [x] 처음 실행했을 때는 오늘 날짜의 데이터를 표시, 데이터가 없으면 미표시
- [x] 날짜 선택했을 때는 선택된 날짜의 데이터를 표시, 없으면 미표시
- [x] FloatingButton 눌렀을 때 SaveMyInfoView를 표시 (modal)
- [x] SaveMyInfoView에서 돌아왔을 때 데이터 리로드
