### ISSUE TITLE
[DESIGN] SaveMyInfo View 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#38]
## Description

- SaveMyInfo View 구성

## Tasks

- [x] 초기화 설정 - MyInfo 값, 선택 날짜 넘겨주기
- [x] 선택 날짜 label
- [x] 선택 날짜 표시 label
- [x] 내 정보 label
- [x] myInfo 타이틀 label 3개
- [x] myInfo textField 3개
- [x] 저장 버튼
