### ISSUE TITLE
[FEATURE] Category 수정, 삭제 기능 연결

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#51]
## Description

- Category 수정, 삭제 기능 연결

## Tasks

- [x] 옵션 버튼 탭하면 액션시트 표시
- [x] 수정 탭하면 Category Edit View 로 이동
- [x] 이동할 때 카테고리 이름 같이
- [x] 저장 버튼 누르면 똑같이 작동
- [x] 삭제하기
- [x] 삭제 후 화면 갱신
