### ISSUE TITLE
[FEATURE] Exercise Edit View 기능 연결

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#55]
## Description

- Exercise Edit View 기능 연결

## Tasks

- [x] URL 검사 - youtubue 인지 검사, shorts도 가능함
- [x] 저장한 카테고리 보여주기
- [x] 추가하기에 Category Edit View 연결
- [x] 카테고리 선택 후 돌아오면 lable 선택한 카테고리로 변경
- [x] 저장 버튼 눌렀을 때 URL 공란 체크, 카테고리 선택 체크
- [x] 저장하고 전 화면으로 돌아가기
