### ISSUE TITLE
[FEATURE] Exercise 기능 연결

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#58]
## Description

- Exercise 기능 연결

## Tasks

- [x] 데이터 없을 때는 데이터 없다고 Label로 표시
- [x] 데이터 있을 때는 화면에 불러오기
- [x] 옵션 메뉴 연결
- [x] 수정하기 누르면 Exiercise edit view로 이동
- [x] 이 때, URL은 수정 불가능 카테고리, 메모 수정 가능 
- [x] 삭제하기 누르면 삭제하고 화면 갱신
