### ISSUE TITLE
[FEATURE] SearchView 기능 연결

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#67]
## Description

- SearchView 기능 연결

## Tasks

- [x] underline 애니메이션 추가   
- [x] 타이틀에서 검색 결과 보여주기
- [x] 메모에서 검색 결과 보여주기
- [x] Cell 탭했을 때 webview 연결
- [x] 옵션 버튼 연결
