### ISSUE TITLE
[FEATURE] 최근 검색어 기능 연결

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#69]
## Description

- 최근 검색어 기능 연결

## Tasks

- [x] 검색어 엔터 누르면 최근 검색어에 저장
- [x] 검색어 하나 삭제
- [x] 검색어 전체 삭제 
- [x] 검색어 누르면 검색창에 표시되고 검색 결과 표시
