### ISSUE TITLE
[DESIGN] Firebase 추가에 따른 회원 가입 view 추가 

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#90]
## Description

- Firebase 추가에 따른 회원 가입 view 추가 

## Tasks

- [x] email, password textfield 추가
- [x] 현 버튼 위치 이동
- [x] 비밀번호 가시성 토글 버튼 추가
- [x] 스크롤뷰 추가
- [x] sns 회원 가입 이미지 추가
