### ISSUE TITLE
[DESIGN] SignInViewController Refactoring

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DeietLog-MVVM#91]
## Description

- SignInViewController를 여러 part의 View로 만들어서 관리하기
- text 공통 관리

## Tasks

- [x] DIET LOG part
- [x] 회원가입 / 로그인 part
- [x] SNS 로그인 part
- [x] Text 공통 관리
